#ifndef QCFFMPEGPLAYECOMMONS_H
#define QCFFMPEGPLAYECOMMONS_H

enum ConnectionStates {
    CONNECTION_STATE_CONNECTED,
    CONNECTION_STATE_CONNECTED_DATA_RECEIVED,
    CONNECTION_STATE_CONNECTING,
    CONNECTION_STATE_IDLE,
};

#endif // QCFFMPEGPLAYECOMMONS_H
